web/tabu/tabu/urls.py
from django.conf.urls import patterns, include, url  # lint:ok

from common import views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Login
    (r'^accounts/', include('allauth.urls')),

    # RPC
    url(r'^rpc/', views.rpc, name="rpc"),

    # Cards
    url(r'^cards/$', views.cards, name='cards'),
    url(r'^get_languages/$', views.get_languages, name='get_languages'),
    url(r'^get_cards/$', views.get_cards, name='get_cards'),

    # Game
     url(r'^how_to_play/$', views.how_to_play, name='how_to_play'),
     url(r'^game/$', views.game, name='game'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^contact/$', views.contact, name='contact'),
    # Home
     url(r'^$', views.home, name='home'),
)

web/tabu/tabu/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User


class Language(models.Model):
    lang = models.CharField(max_length=200, unique=True)
    user = models.ForeignKey(User, blank=True, null=True,
                             on_delete=models.SET_NULL)


class Card(models.Model):
    user = models.ForeignKey(User, blank=True, null=True,
                             on_delete=models.SET_NULL)
    lang = models.CharField(max_length=200)
    mainword = models.CharField(max_length=300)
    word1 = models.CharField(max_length=300)
    word2 = models.CharField(max_length=300)
    word3 = models.CharField(max_length=300)
    word4 = models.CharField(max_length=300)
    word5 = models.CharField(max_length=300)

    class Meta:
        unique_together = ('lang', 'mainword',)


def add_language(lang, user):
    result = {}
    try:
        lang = lang.title()
        langobj, created = Language.objects.get_or_create(lang=lang, user=user)
        if created:
            langobj.save()
            result["language"] = lang
        else:
            result["error"] = "Language %s already exists" % lang
    except:
        result["error"] = "Language couldn't be added."
    return result


def get_languages():
    return Language.objects.values_list('lang', flat=True).order_by('lang')


def get_cards(lang):
    cards = Card.objects.filter(lang=lang).values_list(
        'mainword', "word1", "word2", "word3", "word4", "word5")
    return cards


def add_card(lang, mainword, word1, word2, word3, word4, word5, user):
    result = {}
    try:
        lang = lang.title()
        mainword = mainword.title()
        word1 = word1.title()
        word2 = word2.title()
        word3 = word3.title()
        word4 = word4.title()
        word5 = word5.title()
        cardobj, created = Card.objects.get_or_create(lang=lang, user=user,
            mainword=mainword, word1=word1, word2=word2, word3=word3,
            word4=word4, word5=word5)
        if created:
            cardobj.save()
            result["card"] = mainword
        else:
            result["error"] = "Card %s already exists" % mainword
    except:
        result["error"] = "Card couldn't be added."
    return result

web/tabu/tabu/common/views.py
# -*- coding: utf-8 -*-
import random
from utils import render_response
from django.http import HttpResponse
from django.utils import simplejson
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from tabu import models


def home(request):
    """Home Page."""
    return render_response(request, 'index.html')


@login_required
def cards(request):
    """Cards Page."""
    langs = models.get_languages()
    data = {"langs": langs}
    return render_response(request, 'cards.html', data)


def how_to_play(request):
    """Setup page."""
    return render_response(request, 'how_to_play.html')


def game(request):
    """Game Page."""
    if request.method == 'POST':
        try:
            lang = request.POST['selCombo']
            team1 = request.POST['first_team']
            team2 = request.POST['second_team']
            players = int(request.POST['players'])
            rounds = int(request.POST['rounds'])
            if not team1 or not team2 or players < 2 or rounds < 1:
                raise Exception()

            cards = list(models.get_cards(lang))
            random.shuffle(cards)
            data = {"team1": team1, "team2": team2, "players": players,
                "rounds": rounds, "cards": cards}
            return render_response(request, 'tabu/game_page.html', data)
        except:
            langs = models.get_languages()
            data = {"langs": langs, 'error': "Missing or Invalid data."}
            return render_response(request, 'tabu/setup_page.html', data)
    else:
        langs = models.get_languages()
        data = {"langs": langs}
        return render_response(request, 'tabu/setup_page.html', data)


def contact(request):
    """Game Page."""
    return render_response(request, 'contacts.html')


@require_POST
def rpc(request):
    newlang = request.POST['newlanguage']
    result = {}
    if newlang:
        result = models.add_language(newlang, request.user)
    else:
        lang = request.POST['selCombo']
        mainword = request.POST['mainword']
        word1 = request.POST['word1']
        word2 = request.POST['word2']
        word3 = request.POST['word3']
        word4 = request.POST['word4']
        word5 = request.POST['word5']
        result = models.add_card(lang, mainword, word1, word2, word3, word4,
            word5, request.user)
    data = simplejson.dumps(result)

    return HttpResponse(data, mimetype='application/json')


def get_cards(request):
    cards = list(models.get_cards(request.GET['language']))
    random.shuffle(cards)
    data = simplejson.dumps(cards)

    return HttpResponse(data, mimetype='application/json')


def get_languages(request):
    langs = list(models.get_languages())
    data = simplejson.dumps(langs)

    return HttpResponse(data, mimetype='application/json')

web/tabu/tabu/templates/base/base.html
{% load staticfiles %}
{% load url from future %}

<!DOCTYPE html>
<head>
    <!-- Basic Page Needs -->
    <meta charset="utf-8">
    <title>Tabu Game!</title>
    <meta name="description" content="Tabu Party Game">
    <meta name="author" content="Emilio Ramirez, Diego Sarmentero">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Start CSS Style
    =======================================================================================-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" /><!-- Main Style -->
    <!-- Color Skins -->
    <link rel="stylesheet" href="{% static 'css/skins/blue.css' %}" name="skins">
    <!-- Layout Style -->
    <link rel="stylesheet" href="{% static 'css/layout/wide.css' %}" name="layout">
    <!-- Style Switcher Box -->
    <link rel="stylesheet" href="{% static 'css/layout/switcher.css' %}">
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
</head>

<body onload="prettyPrint()">

    <div id="wrap" class="boxed">

    <div class="container">

    <!-- Header
    =========================================================================================================== -->
    <header>

        <!-- Logo + menu -->
        <div class="logoWrapper">
                <div class="row">
                	<!-- logo - font -->
                    <div class="span6 logo">
                        <span class="logoFirst">T</span><a href="{% url 'home' %}">abu Game!</a>
                        <span class="small">Have fun guessing words!</span>
                    </div>

                    <!-- SOCIALS -->
                    <div class="span6">
                        <ul class="tooltip-title top-social">
                            <li><a href="https://twitter.com/emilioramirez" rel="tooltip" title="emilioramirez" class="social2-top"></a></li>
                            <li><a href="https://twitter.com/diegosarmentero" rel="tooltip" title="diegosarmentero" class="social2-top"></a></li>
                        </ul>
                    </div>
                    <!--/SOCIALS-->
                </div><!--/row-->

            <!-- STRAT MENU
            ============================================================ -->
            <nav class="container menu">
                	<div class="row">
                        <div class="span9">
                            <ul id="jMenu">
                              <li><a href="#" class="fNiv">Home<br/>
                                <span class="smallText">All starts here</span></a>
                                <ul>
                                  <li><a href="{% url 'home' %}">Home</a></li>
                                  {% if user.username %}
                                    <li><a href="{% url 'account_logout' %}">Logout</a></li>
                                  {% else %}
                                    <li><a href="{% url 'account_login' %}">Login</a></li>
                                  {% endif %}
                                  <li><a href="{% url 'cards' %}">Create Card</a></li>
                              </ul>
                            </li>
                            <li><a href="{% url 'how_to_play' %}" class="fNiv">How to Play?<br/>
                                <span class="smallText">Learn to play Tabu in 6 steps</span></a>
                            </li>
                              <!--li><a href="{% url 'contact' %}" class="fNiv last">Contact<br/>
                                <span class="smallText">Send a message to us</span></a></li>
                            </li-->
                            {% if user.username %}
                            <li><a href="{% url 'account_logout' %}" class="fNiv">Logout<br/>
                                <span class="smallText">(Close session)</span></a>
                            </li>
                            {% else %}
                            <li><a href="{% url 'account_login' %}" class="fNiv">Login<br/>
                                <span class="smallText">(Access)</span></a>
                            </li>
                            {% endif %}
                          </ul>
                      </div>

                   </div><!--/row-->
            </nav>
            <!--/MENU-->

        </div><!--/logoWrapper-->

    </header>

    {% block content %}{% endblock %}

<!-- Footer
    ============================================================================================================= -->
    <div class="container darkBg">
        <footer>
                <div id="mainFooter">
                        <div class="row">
                            <!-- About Us -->
                            <div class="span2">
                                <h4>About Us</h4>
                                <p>
                                    Website created by: Diego Sarmentero and Emilio Ramirez
                                </p>
                            </div>
                            <div class="span4">
                            </div>
                            <div class="span4">
                            </div>
                            <!-- Source Code -->
                            <div class="span2">
                                <h4>Source Code</h4>
                                <address>
                                  <strong>Github Repo</strong><br/>
                                  <a href="https://github.com/diegosarmentero/tabu">https://github.com/diegosarmentero/tabu</a>
                                </address>
                            </div>
                        </div>

                        <!-- Copy rights + subscribtion area -->
                        <div class="row bord-top">
                            <div class="span6 copyrights">
                          Copyright 2013  Tabu</a>
                            </div>

                            <div class="span6">
                                <ul class="footer-social tooltip-title">
                                <li><a href="https://twitter.com/emilioramirez" rel="tooltip" title="emilioramirez"><i class="icon-twitter-sign"></i></a></li>
                                <li><a href="https://twitter.com/diegosarmentero" rel="tooltip" title="diegosarmentero"><i class="icon-twitter-sign"></i></a></li>
                                </ul>
                            </div>
                        </div>

                </div><!--/mainFooter-->
            </footer>
        </div><!--/container-->
        </div><!--/wrap-->

    <!-- javascript
    ============================================================================================================= -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block scripts %}
    <script src="{% static 'js/jquery.js' %}"></script><!-- Main JQuery -->
    <script src="{% static 'js/bootstrap.js' %}"></script><!-- Bootstrap Js main file -->
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script><!-- easing.1.3 -->
    <script src="{% static 'js/jquery.cookie.js' %}"></script><!-- cookie -->
    <script src="{% static 'js/jquery-ui-1.8.20.custom.min.js' %}"></script><!-- jquery-ui -->
    <script src="{% static 'js/jMenu.jquery.js' %}"></script><!-- Nav menu -->
    <script defer src="{% static 'js/jquery.flexslider.js' %}"></script><!-- Flex Basic carousel -->
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script><!-- PrettyPhoto -->
    <script src="{% static 'js/jquery.liquid-slider-0.1.js' %}"></script><!-- Testimonials - text slider -->
    <script src="{% static 'js/jquery.tweet.js' %}"></script><!-- Twitter plugin -->
    <script src="{% static 'js/jflickrfeed.min.js' %}"></script><!-- jQuery Flickr -->
    <script src="{% static 'js/jquery.ui.totop.js' %}" ></script><!-- Go to top -->
    <script src="{% static 'js/filterable.pack.js' %}"></script><!-- Filter portfolio -->
    <script src="{% static 'js/audio.min.js' %}"></script><!-- audio player -->
    <script src="{% static 'js/prettify.js' %}"></script><!-- YOU CAN REMOVE IT // it's associated with shortcodes preview boxes -->
    <script defer src="{% static 'rs-plugin/js/jquery.themepunch.plugins.min.js' %}"></script><!--REVOLUTION SLIDER-->
    <script defer src="{% static 'rs-plugin/js/jquery.themepunch.revolution.min.js' %}"></script><!--REVOLUTION SLIDER-->
    <script src="{% static 'js/custom.js' %}"></script><!-- All scripts that shuold be on html file collected here -->
    {% endblock scripts %}

</body>
</html>

web/tabu/tabu/templates/cards.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% load url from future %}
{% load socialaccount %}

{% block scripts %}
{{ block.super }}
<script src="{% static 'js/actions.js' %}"></script>
<script type="text/javascript" src="{% static 'js/pnotify-1.2.0/jquery.pnotify.min.js' %}"></script>
<link href="{% static 'js/pnotify-1.2.0/jquery.pnotify.default.css' %}" rel="stylesheet" type="text/css" />
{% endblock scripts %}

{% block content %}
<div class="main">
    <div class="container">
        <div class="row row-login">
            <div class="span5 sidebar_content">
                <div class="wrapper-login">
                    <div class="container">
                        <div class="row">
                            <div class="login-content span5 offset1">
                                <div class="header-login well">
                                    <h3>Create New Card</h3>
                                </div>
                                <form id="form_card" class="well">
                                {% csrf_token %}
                                <div id="languageCombo" style="display: inline-block;">
                                    <p><label for="id_language">Language:</label>
                                        <p id="id_language" name="language">
                                            <select id="selectCombo" name="selCombo" size=1>
                                                {% for langname in langs %}
                                                    <option value="{{ langname }}">{{ langname }}</option>
                                                {% endfor %}
                                            </select>
                                            <input id="addNewLanguage" type="button" class="btn btn-info" value="+ Add New Language">
                                        <p>
                                    </p>
                                </div>
                                <div id="hiddenNewLanguage" style="display: none;">
                                    <p>
                                    <label for="id_newlanguage">New Language:</label> <input id="id_newlanguage" name="newlanguage" placeholder="New Language"/>
                                    <input id="createLanguage" type="button" class="btn btn-info" value="Create">
                                    <input id="cancelLanguage" type="button" class="btn btn-info" value="Cancel">
                                    </p>
                                </div>
                                <div id="dataCard" style="display: inline-block;">
                                <p><label for="id_mainword">Main Word:</label> <input id="id_mainword" name="mainword" placeholder="Main Word"/></p>
                                <p><label for="id_word1">Word 1:</label> <input id="id_word1" name="word1" placeholder="First related word"/></p>
                                <p><label for="id_word2">Word 2:</label> <input id="id_word2" name="word2" placeholder="Second related word"/></p>
                                <p><label for="id_word3">Word 3:</label> <input id="id_word3" name="word3" placeholder="Third related word"/></p>
                                <p><label for="id_word4">Word 4:</label> <input id="id_word4" name="word4" placeholder="Fourth related word"/></p>
                                <p><label for="id_word5">Word 5:</label> <input id="id_word5" name="word5" placeholder="Fifth related word"/></p>
                                  <input type="submit" class="btn btn-info" value="Add Card">
                                </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end content settings -->
            </div>
        </div>
    </div><!-- end container -->
</div><!-- end main -->

{% endblock %}

web/tabu/tabu/templates/game_example.html
{% load staticfiles %}
{% load url from future %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/jquerymobile/jquery.mobile-1.3.1.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquerymobile/jquery.mobile.structure-1.3.1.css' %}" />
    
    <script src="{% static 'js/jquerymobile/jquery-v1.9.1.js' %}"></script>
    <script src="{% static 'js/jquerymobile/jquery.mobile-1.3.1.js' %}"></script>

	<title>Tabu</title>
</head> 
<body> 
    <!-- PAGE Now playing -->
    <div data-role="page" id="nowplaying" >
        <div data-role="header" data-id="foooooo" data-position="fixed">
            <div data-role="navbar">
                <ul>
                    <li><a data-icon="star" class="ui-btn-active ui-state-persist" href="#nowplaying" data-transition="slide" >Current Playlist</a></li>
                    <li><a data-icon="plus" href="#latests" data-transition="slide">Last Voted</a></li>
                    <li><a data-icon="search" href="#search" data-transition="slide">Search</a></li>
                </ul>
            </div>
        </div>
        <div data-role="content">
            <ul data-role="listview">
                <li data-theme="a">
                    <a href="#">
                        <h3>1. Música 1 <span class="ui-li-count">12</span></h3>
                        <p><strong>Artista, Album</strong></p>
                        <p>00:15 - 4:35</p>
                    </a>
                    <a href="#" data-icon="minus" data-theme="b">minus</a>
                </li>

                <li>
                    <a href="#">2. Música 2 <span class="ui-li-count">5</span></a>
                    <a href="#" data-icon="plus" data-theme="a">plus</a>
                </li>
                <li>
                    <a href="#">3. Música 3 <span class="ui-li-count">1</span></a>
                    <a href="#" data-icon="plus" data-theme="a">plus</a>
                </li>
                <li>
                    <a href="#">4. Música 4 <span class="ui-li-count">5</span></a>
                    <a href="#" data-icon="plus" data-theme="a">plus</a>
                </li>
                <li>
                    <a href="#">5. Arjona 5 <span class="ui-li-count">6</span></a>
                    <a href="#" data-icon="plus" data-theme="a">plus</a>
                </li>
            </ul>
        </div>
    </div>
    <!-- /PAGES Now Playing -->
    <!-- PAGE Latests -->
    <div data-role="page" id="latests" >
        <div data-role="header" data-id="foooooo" data-position="fixed">
            <div data-role="navbar">
                <ul>
                    <li><a data-icon="star" href="#nowplaying" data-transition="slide" data-direction="reverse">Current Playlist</a></li>
                    <li><a data-icon="plus" href="#latests" class="ui-btn-active ui-state-persist" data-transition="slide">Last Voted</a></li>
                    <li><a data-icon="search" href="#search" data-transition="slide">Search</a></li>
                </ul>
            </div>
        </div>
        <div data-role="content">
            <ol data-role="listview">
                <li>
                    <a href="#">Música 1</a> <span class="ui-li-count">5</span>
                    <a href="#" data-icon="plus">plus</a>
                </li>
                <li>
                    <a href="#">Música 2 <span class="ui-li-count">5</span></a>
                    <a href="#" data-icon="plus">plus</a>
                </li>
                <li>
                    <a href="#">Música 3 <span class="ui-li-count">1</span></a>
                    <a href="#" data-icon="plus">plus</a>
                </li>
                <li>
                    <a href="#">Música 4 <span class="ui-li-count">5</span></a>
                    <a href="#" data-icon="plus">plus</a>
                </li>
                <li>
                    <a href="#">Arjona 5 <span class="ui-li-count">6</span></a>
                    <a href="#" data-icon="plus">plus</a>
                </li>
            </ol>
        </div>
    </div>
    <!-- /PAGE Latests -->
    <!-- PAGE Search -->
    <div data-role="page" id="search">
        <div data-role="header" data-id="foooooo" data-position="fixed">
            <div data-role="navbar">
                <ul>
                    <li><a data-icon="star" href="#nowplaying" data-transition="slide" data-direction="reverse">Current Playlist</a></li>
                    <li><a data-icon="plus" href="#latests" data-transition="slide" data-direction="reverse">Last Voted</a></li>
                    <li><a data-icon="search" href="#search" class="ui-btn-active ui-state-persist" data-transition="slide">Search</a></li>
                </ul>
            </div>
        </div>
        <div data-role="content">
            <div data-role="fieldcontain">
                <label for="search-basic">Search Input:</label>
                <input type="search" name="search" id="search-basic" value="" />
            </div>
            <ul data-role="listview">
                <li><a href="#" >Arjona 1</a><a href="#" data-icon="plus"></a></li>
                <li><a href="#" >Arjona 2</a><a href="#" data-icon="plus"></a></li>
            </ul>
        </div>
    </div>
    <!-- /PAGE Search -->
</body>
</html>

web/tabu/tabu/templates/how_to_play.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% load url from future %}
{% load socialaccount %}

{% block scripts %}
{{ block.super }}
<script src="{% static 'js/actions.js' %}"></script>
<script type="text/javascript" src="{% static 'js/pnotify-1.2.0/jquery.pnotify.min.js' %}"></script>
<link href="{% static 'js/pnotify-1.2.0/jquery.pnotify.default.css' %}" rel="stylesheet" type="text/css" />
{% endblock scripts %}

{% block content %}
<div class="main">
    <div class="container">
        <div class="row row-login">
            <div class="span9 sidebar_content">
                <div class="wrapper-login">
                    <div class="container">
                        <div class="row">
                            <div class="login-content span9 offset1">
                                <div class="header-login well">
                                    <h3>How to Play</h3>
                                </div>
                                <p>
                                    Tabu is a word guessing party game. The objective of the game is for a player to have his/her partner(s) guess the word on his/her card without using the word itself or five additional words listed on the card.
                                </p>
                                <p>
                                    1) Divide the players into two teams.
                                </p>
                                <p>
                                    2) Choose one person from a team to be the first clue giver. She/He sits opposite of their team and start the round of Tabu, flipping the cards when necessary. The card should be hidden from their team but visible to at least one of her/his opponents. That opponent should pay attention to press Incorrect when one of the forbidden words is mentioned.
                                </p>
                                <p>
                                    3) Give verbal clues to your teammates to help them guess the word placed at the top of the card. Your clues can be sentences or single words. Do not use the words that are shown on the Tabu list on the card. The list on the card contains a number of words or terms that are considered \"tabu/taboo,\" and therefore cannot be said aloud by the clue giver. The listed words, and any parts or forms of them, are forbidden as clues. For instance, you cannot say the words "baby" or "sitter" if the word "babysitter" is listed. You also cannot say "work" if one of the words listed is "work".
                                </p>
                                <p>
                                    4) Score one point for the clue giver's team for each word they guess correctly, pressing "Correct". There is no penalty for wrong answers.
                                </p>
                                <p>
                                    5) You can flip the card and move on to the next Card if you want.
                                </p>
                                <p>
                                    6) Press the "Incorrect" button if you hear the clue giver use the Tabu word, or any of the related ones. If this happens, the clue giver must move on to another word. The clue giver may continue giving clues until the time (one minute) expires. The team with the biggest number of words guessed at the end of all the rounds wins.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end content settings -->
            </div>
        </div>
    </div><!-- end container -->
</div><!-- end main -->

{% endblock %}

web/tabu/tabu/templates/tabu/setup_page.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% load url from future %}
{% load socialaccount %}

{% block scripts %}
{{ block.super }}
<script src="{% static 'js/actions.js' %}"></script>
<script type="text/javascript" src="{% static 'js/pnotify-1.2.0/jquery.pnotify.min.js' %}"></script>
<link href="{% static 'js/pnotify-1.2.0/jquery.pnotify.default.css' %}" rel="stylesheet" type="text/css" />
{% endblock scripts %}

{% block content %}
<div class="main">
    <div class="container">
        <div class="row row-login">
            <div class="span5 sidebar_content">
                <div class="wrapper-login">
                    <div class="container">
                        <div class="row">
                            <div class="login-content span5 offset1">
                                <div class="header-login well">
                                    <h3>Setup Game!</h3>
                                </div>
                                <form id="form_setup" class="well" method="POST">
                                {% csrf_token %}
                                {% if error %}
                                    <div id="hiddenError">
                                {% else %}
                                    <div id="hiddenError" style="display: none;">
                                {% endif %}
                                    <p><font color="red">{{ error }}</font></p>
                                </div>
                                <div id="languageCombo" style="display: inline-block;">
                                    <p><label for="id_language">Language:</label>
                                        <p id="id_language" name="language">
                                            <select id="selectCombo" name="selCombo" size=1>
                                                {% for langname in langs %}
                                                    <option value="{{ langname }}">{{ langname }}</option>
                                                {% endfor %}
                                            </select>
                                        <p>
                                    </p>
                                </div>
                                <div id="dataTeam" style="display: inline-block;">
                                <p><label for="id_first_team">First Team Name:</label> <input id="id_first_team" name="first_team" placeholder="First Team Name"/></p>
                                <p><label for="id_second_team">Second Team Name:</label> <input id="id_second_team" name="second_team" placeholder="Second Team Name"/></p>
                                <p><label for="id_players">Number of Players per Team:</label> <input id="id_players" name="players" placeholder="Number of Players"/></p>
                                <p><label for="id_rounds">Number of Rounds:</label> <input id="id_rounds" name="rounds" placeholder="Number of Rounds"/></p>
                                  <input type="submit" class="btn btn-info" value="Start Game!">
                                </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end content settings -->
            </div>
        </div>
    </div><!-- end container -->
</div><!-- end main -->

{% endblock %}